In [1]:
import numpy as np
import random
import math

from matplotlib import pyplot as plt

In [2]:
# Paramètres
n = m = 18 # nombre de lignes = nombre de colonnes
initial_size = 2 # taille de la fourmilière initiale
max_food_quantity = 500 #quantité maximale de nourriture par source de nourriture
neigh = 1 #voisinage / champ de vision de chaque fourmi

In [9]:
def generate_simple_map(n, m): # n : lignes m : colonnes
    """Préconditions : m > 0 et n > 0, initial_size > 0
    Renvoie un monde de taille n*m avec une fourmilière au centre et un point de nourriture en périphérie"""
    map = np.array([[" " for i in range(0, n)] for j in range(0, n)]) # on crée la matrice vide (avec des 0 partout)
    # on crée la fourmilière au centre
    for i in range(0, initial_size):
        for k in range(0, initial_size):
            map = np.delete(map, m*(n//2 - initial_size//2 + i) + m//2 - initial_size//2 + k) #on copie le monde en enlevant une à une les cases du carré de taille initial_size situé au centre
            map = np.insert(map, m*(n//2 - initial_size//2 + i) + m//2 - initial_size//2 + k, 1) #on remplace les cases initialement vide (avec un 0) par une case "fourmilière" (avec un 1)
            map = np.array([[map[m*j + i] for i in range(0, m)] for j in range(0, n) ])
    
    # on crée un point de nourriture
    food_line = random.randint(0, 2*n//5 - 1) # on définit ainsi la périphérie comme étant les cases du bord de la matrice avec un largeur de n/5
    food_column = random.randint(0, 2*m//5 - 1)
    if food_line > n//5 - 1: # on est sur la périphérie du bas
        food_line = n - 2 - n//5 + food_line
    if food_column > m//5 - 1: # on est sur la périphérie de droite
        food_column = m - 2 - m//5 + food_column
    where = random.sample([food_line, food_column], 1) # on définit une périphérie où se mettre (horizontale ou verticale)
    if where == food_line: # on est sur une périphérie en haut ou en bas
        food_column = random.randint(0, m - 1) # on définit une case au hasard sur cette périphérie
    else : #on est sur une périphérie latérale
        food_line = random.randint(0, n - 1) # on définit une case au hasard sur cette périphérie
    # on place dans la matrice de point de nourriture de quantité aléatoire food_quantity et de position périphérique aléatoire (food_line, food_column)
    food_quantity = random.randint(3, max_food_quantity) # on attribue à ce point de nourriture une certaine quantité de nourriture
    map = np.delete(map, m*food_line + food_column)
    map = np.insert(map, m*food_line + food_column, food_quantity)
    map = np.array([[map[m*j + i] for i in range(0, m)] for j in range(0, n) ])       
    
    return map
print (generate_simple_map(n, m))

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '1' '1' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '1' '1' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' '

In [8]:
def spatial_neighborhood (map, a, b, neigh): #world : List[List[int]], a : int(ligne), b : int(colonne), neigh : int
    
    """Préconditions :0 <= a <= n-1  and 0 <= b <= m-1 and n >= 2*neigh and m >= 2*neigh
    Retourne la matrice des types des voisins de de l'individu en [a, b] avec a la ligne et b la colonne"""
    
    voisin = np.array([[ for i in range(0, 2*neigh + 1)] for j in range(0, 2*neigh + 1)]) #grille vide de la taille du voisinage
    
    world_without_ind = np.delete(map, (m-1)*a + b) #on copie le monde sans l'individu
    world_without_ind = np.insert(world_without_ind, m*a + b, 0) #on remplace la place de l'individu par une case vide (avec un 0)
    world_without_ind = np.array([[world_without_ind[m*j + i] for i in range(0, m)] for j in range(0, n) ]) #on remet le monde sous forme de tableau
    

    if a - neigh >= 0 and a + neigh <= n - 1: # on teste les lignes, il n'y a pas de problème avec les bords (n-1 car les indices commencent à 0)
        if b - neigh >= 0 and b + neigh <= m - 1: #on teste les colonnes, il n'y a pas de problèmes avec les bords
            voisin = np.array([[world_without_ind[a-neigh + j, b-neigh + i] for i in range(0, 2*neigh + 1)] for j in range(0, 2*neigh + 1)]) 
        elif b - neigh < 0: # on atteint le bord gauche de la matrice
            voisin = np.array([[world_without_ind[a - neigh + j, i] for i in range(0, b + neigh + 1)] for j in range(0, 2*neigh + 1)])
        elif b + neigh > m - 1: # on atteint le bord droit
            voisin = np.array([[world_without_ind[a - neigh + j, i] for i in range(b - neigh, m)] for j in range(0, 2*neigh + 1)])
    elif a - neigh < 0 : # on atteint le bord haut
        if b - neigh >= 0 and b + neigh <= m - 1: #on teste les colonnes, il n'y a pas de problèmes avec les bords
            voisin = np.array([[world_without_ind[j, b-neigh + i] for i in range(0, 2*neigh + 1)] for j in range(0, a + neigh + 1)])
        elif b - neigh < 0: # on atteint le bord gauche de la matrice
            voisin = np.array([[world_without_ind[j, i] for i in range(0, b + neigh + 1)] for j in range(0, a + neigh + 1)])
        elif b + neigh > m - 1: # on atteint le bord droit
            voisin = np.array([[world_without_ind[j, i] for i in range(b - neigh, m)] for j in range(0, a + neigh + 1)])
    else : # a + neigh > n - 1
        if b - neigh >= 0 and b + neigh <= m - 1: #on teste les colonnes, il n'y a pas de problèmes avec les bords
            voisin = np.array([[world_without_ind[j, b-neigh + i] for i in range(0, 2*neigh + 1)] for j in range(a - neigh, n)]) #on copie 
        elif b - neigh < 0: # on atteint le bord gauche de la matrice
            voisin = np.array([[world_without_ind[j, i] for i in range(0, b + neigh + 1)] for j in range(a - neigh, n)])
        elif b + neigh > m - 1: # on atteint le bord droit
            voisin = np.array([[world_without_ind[j, i] for i in range(b - neigh, m)] for j in range(a - neigh, n)])
    return voisin

def spatial_relocation (map, a, b, c, d): #map : List[List[int]], a : int(ligne), b : int(colonne), c : int(ligne), d : int(colonne)
    """Préconditions : 0 <= a <= n-1  and 0 <= b <= m-1  and 0 <= c <= n-1  and 0 <= d <= m-1 and n >= 2*neigh and m >= 2*neigh and map[c,d] == 0
    Renvoie le monde dans lequel l'individu de coordonnées [a, b] a été déplacé vers la case vide de coordonnées [c, d]"""
    ant = map[a, b] #on enregistre la cellule à déplacer (une fourmi)
    if map[c, d] == 0:
        # on supprime l'indidu du monde
        map_without_ant = np.delete(map, m*a + b) #on copie le monde sans l'individu
        map_without_ant = np.insert(map_without_ant, m*a + b, 0) #on remplace la place de l'individu par une case vide (avec un 0)
        map_without_ant = np.array([[map_without_ant[m*j + i] for i in range(0, m)] for j in range(0, n) ]) #on remet le monde sous forme de tableau
        # on remplace la case vide par l'individu
        relocation = np.delete(map_without_ant, m*c + d) #on copie le monde sans la case vide
        relocation = np.insert(relocation, m*c + d, ant) #on remplace la place de la case vide par l'individu (avec un cell)
        relocation = np.array([[relocation[m*j + i] for i in range(0, m)] for j in range(0, n) ]) #on remet le monde sous forme de tableau
        return relocation

def ants (map, nb_ants):
    """Precondition : nb_ants >= 0
    Fait apparaitre nb_ants fourmis autour de la fourmilière"""
    ants_map = map
    for k in range(0, n):
        for l in range(0, m):
            if ants_map[k, l] == 0: #on vérifie que la case est vide
                for o in spatial_neighborhood(map, k, l, neigh):
                    for p in o:
                        if p == 1 and nb_ants > 0 : #on regarde si il y a une case fourmilière dans le voisinage
                            if ants_map[k, l] == 0: #on vérifie que la case est vide
                                ants_map = np.delete(ants_map, m*k + l) #on copie le monde en enlevant la case ayant la fourmilière pour voisin
                                ants_map = np.insert(ants_map, m*k + l, 2) #on remplace les cases initialement vide (avec un 0) par une case "fourmi" (avec un 2)
                                ants_map = np.array([[ants_map[m*j + i] for i in range(0, m)] for j in range(0, n) ])
                                nb_ants = nb_ants - 1
    q = 0                            
    while nb_ants > 0: #la fourmilière est entourée de fourmis
        q = q + 1
        for k in range(0, n):
            for l in range(0, m):
                if ants_map[k, l] == 0: #on vérifie que la case est vide
                    for o in spatial_neighborhood(map, k, l, neigh + q):
                        for p in o:
                            if p == 1 and nb_ants > 0 : #on regarde si il y a une case fourmilière dans le voisinage + q
                                if ants_map[k, l] == 0: #on vérifie que la case est vide
                                    ants_map = np.delete(ants_map, m*k + l) #on copie le monde en enlevant la case ayant la fourmilière pour voisin
                                    ants_map = np.insert(ants_map, m*k + l, 2) #on remplace les cases initialement vide (avec un 0) par une case "fourmi" (avec un 2)
                                    ants_map = np.array([[ants_map[m*j + i] for i in range(0, m)] for j in range(0, n) ])
                                    nb_ants = nb_ants - 1                        
    return ants_map


def no_food(map, a, b):
    """Précondition : 0 >= a >= n, 0 >= b >= m
    Renvoie True si il n'y a pas de nourriture à dans le voisinage de la case et False sinon."""
    for i in spatial_neighborhood(map, a, b, 1):
        for j in i:
            if j >= 3: #il y a de la nourriture dans le voisinage de la case
                return False
    return True

def one_food_quest (map, a, b):
    """Précondition : 0 >= a >= n, 0 >= b >= m
    Si la case [a, b] est une fourmi, renvoie la matrice après son déplacement aléatoire sans retourner sur ses pas
    sinon renvoie la matrice initiale"""
    move_map = map
    move_line = a #ligne de la fourmi
    move_column = b #colonne de la fourmi
    previous_location = - 10 #on retient la position précédente pour ne pas y revenir
    if move_map[a, b] == 2 : #la case sélectionnée est une fourmi
        while no_food(move_map, move_line, move_column): #il n'y a pas de nourriture à coté de la fourmi            
            next_move = random.randint(0, 3) #on décide le procahin mouvement au hasard
            if next_move == 0 and previous_location != 2:
                if move_line > 0 and move_map[move_line - 1, move_column] == 0: #la prochaine case existe et est vide
                    move_map = spatial_relocation(move_map, move_line, move_column, move_line - 1, move_column) #déplacement vers le haut
                    previous_location = next_move
                    move_line = move_line - 1
            if next_move == 1 and previous_location != 3:
                if move_column < m - 1 and move_map[move_line, move_column + 1] == 0:
                    move_map = spatial_relocation(move_map, move_line, move_column, move_line, move_column + 1) #déplacement vers la droite
                    previous_location = next_move                  
                    move_column = move_column + 1
            if next_move == 2 and previous_location != 0:
                if move_line < n - 1 and move_map[move_line + 1, move_column] == 0:
                    move_map = spatial_relocation(move_map, move_line, move_column, move_line + 1, move_column) #déplacement vers le bas
                    previous_location = next_move
                    move_line = move_line + 1
            if next_move == 3 and previous_location != 1:
                if move_column > 0 and move_map[move_line, move_column - 1] == 0:
                    move_map = spatial_relocation(move_map, move_line, move_column, move_line, move_column - 1) #déplacement vers la gauche
                    previous_location = next_move
                    move_column = move_column - 1
            print(move_map)
    return move_map
            

def ants_food_quest(map):
    
    """Effectue le déplacement aléatoire de toutes les fourmis jusqu'à ce qu'il y en ait une qui trouve de la nourriture"""
    move_map = map
    move_line = - 1
    move_column = - 1
    food = False
    while food == False:
        for i in range(0, n):
            for j in range(0, m):
                if move_map[i, j] == 2 : #la case sélectionnée est une fourmi
                    next_move = random.randint(0, 3) #on décide le prochain mouvement au hasard
                    if next_move == 0:
                        if i > 0 and move_map[i - 1, j] == 0: #la prochaine case existe et est vide
                            move_map = spatial_relocation(move_map, i, j, i - 1, j) #déplacement vers le haut
                            move_line = i + 1
                            move_column = j
                    if next_move == 1:
                        if j < m - 1 and move_map[i, j + 1] == 0:
                            move_map = spatial_relocation(move_map, i, j, i, j + 1) #déplacement vers la droite
                            move_line = i
                            move_column = j + 1
                    if next_move == 2:
                        if i < n - 1 and move_map[i + 1, j] == 0:
                            move_map = spatial_relocation(move_map, i, j, i + 1, j) #déplacement vers le bas
                            move_line = i - 1
                            move_column = j
                    if next_move == 3:
                        if j > 0 and move_map[i, j - 1] == 0:
                            move_map = spatial_relocation(move_map, i, j, i, j - 1) #déplacement vers la gauche
                            move_line = i
                            move_column = j - 1
                    if no_food(move_map, move_line, move_column) == False:
                        print(move_line, move_column)
                        food = True
        print(move_map)
        print(food)
    return move_map

print(one_food_quest(ants(generate_simple_map(n, m), 1), 7, 7))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0

In [11]:
>

SyntaxError: invalid syntax (<ipython-input-11-18af074ce652>, line 1)